export const TAB_CLICK = 'TAB_CLICK';
export const CLEAR_PREVIOUS_DATA = 'CLEAR_PREVIOUS_DATA';
export const FETCH_SEARCH_PHOTOS_PENDING = 'FETCH_SEARCH_PHOTOS_PENDING';
export const FETCH_SEARCH_PHOTOS_SUCCESS = 'FETCH_SEARCH_PHOTOS_SUCCESS';
export const FETCH_SEARCH_PHOTOS_NO_DATA = 'FETCH_SEARCH_PHOTOS_NO_DATA';
export const FETCH_SEARCH_PHOTOS_ERROR = 'FETCH_SEARCH_PHOTOS_ERROR';
export const FETCH_MORE_SEARCH_PHOTOS = 'FETCH_MORE_SEARCH_PHOTOS';
export const PHOTO_CLICK = 'PHOTO_CLICK';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const FETCH_SEARCH_COLLECTIONS_PENDING =
  'FETCH_SEARCH_COLLECTIONS_PENDING';
export const FETCH_SEARCH_COLLECTIONS_SUCCESS =
  'FETCH_SEARCH_COLLECTIONS_SUCCESS';
export const FETCH_SEARCH_COLLECTIONS_NO_DATA =
  'FETCH_SEARCH_COLLECTIONS_NO_DATA';
export const FETCH_SEARCH_COLLECTIONS_ERROR = 'FETCH_SEARCH_COLLECTIONS_ERROR';
export const FETCH_MORE_SEARCH_COLLECTIONS = 'FETCH_MORE_SEARCH_COLLECTIONS';
export const FETCH_SEARCH_USERS_PENDING = 'FETCH_SEARCH_USERS_PENDING';
export const FETCH_SEARCH_USERS_SUCCESS = 'FETCH_SEARCH_USERS_SUCCESS';
export const FETCH_SEARCH_USERS_NO_DATA = 'FETCH_SEARCH_USERS_NO_DATA';
export const FETCH_SEARCH_USERS_ERROR = 'FETCH_SEARCH_USERS_ERROR';
export const FETCH_MORE_SEARCH_USERS = 'FETCH_MORE_SEARCH_USERS';
export const getSearchPhotosPageToLoad = state =>
  state.search.photos.pageToLoad;
export const getSearchCollectionsPageToLoad = state =>
  state.search.collections.pageToLoad;
export const getSearchUsersPageToLoad = state => state.search.users.pageToLoad;
