export const TAB_CLICK = 'TAB_CLICK';
export const FETCH_COLLECTION_DATA_PENDING = 'FETCH_COLLECTION_DATA_PENDING';
export const FETCH_COLLECTION_DATA_SUCCESS = 'FETCH_COLLECTION_DATA_SUCCESS';
export const FETCH_COLLECTION_DATA_ERROR = 'FETCH_COLLECTION_DATA_ERROR';
export const FETCH_COLLECTION_PHOTOS_PENDING =
  'FETCH_COLLECTION_PHOTOS_PENDING';
export const FETCH_COLLECTION_PHOTOS_SUCCESS =
  'FETCH_COLLECTION_PHOTOS_SUCCESS';
export const FETCH_COLLECTION_PHOTOS_NO_MORE_DATA =
  'FETCH_COLLECTION_PHOTOS_NO_MORE_DATA';
export const FETCH_COLLECTION_PHOTOS_ERROR = 'FETCH_COLLECTION_PHOTOS_ERROR';
export const FETCH_RELATED_PENDING = 'FETCH_RELATED_PENDING';
export const FETCH_RELATED_SUCCESS = 'FETCH_RELATED_SUCCESS';
export const FETCH_RELATED_NO_DATA = 'FETCH_RELATED_NO_DATA';
export const FETCH_RELATED_ERROR = 'FETCH_RELATED_ERROR';
export const FETCH_MORE_COLLECTION_PHOTOS = 'FETCH_MORE_COLLECTION_PHOTOS';
export const OPEN_PHOTO_MODAL = 'OPEN_PHOTO_MODAL';
export const CLOSE_PHOTO_MODAL = 'CLOSE_PHOTO_MODAL';
export const getPageToLoad = state => state.collection.pageToLoad;
export const DELETE_PREVIOUS_DATA = 'DELETE_PREVIOUS_DATA';
